# Generated by Django 4.0.3 on 2023-06-06 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("sales_rest", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sale",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="sales_rest.customer",
            ),
        ),
        migrations.AlterField(
            model_name="sale",
            name="salesperson",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="sales_rest.salesperson",
            ),
        ),
        migrations.AlterField(
            model_name="salesperson",
            name="employee_id",
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
