# Generated by Django 4.0.3 on 2023-06-06 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0003_status_alter_appointment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='name',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
