# Generated by Django 4.0.3 on 2023-06-06 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0004_alter_status_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='technician',
            name='employee_user_name',
            field=models.CharField(default=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='technician',
            name='employee_id',
            field=models.IntegerField(),
        ),
    ]
