# Generated by Django 4.0.3 on 2023-06-06 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0005_technician_employee_user_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='technician',
            name='employee_user_name',
        ),
        migrations.AlterField(
            model_name='technician',
            name='employee_id',
            field=models.CharField(max_length=50),
        ),
    ]
